### ISSUE TITLE
Code Sign error: The identity '3rd Party Mac Developer Application' doesn't match any valid, non-expired certificate/private key pair in your keychains

### ISSUE THREAD

**Issue by pvagithub** [iamleeg/LogViewer#1]
When i build project, e get error as this link
https://github.com/robrix/Grid/issues/9

**Comment by iamleeg** [comment]
You need to be on the Mac developer program to sign the app using an Apple-signed certificate. If you aren't a member, you should create a self-signed certificate and use that to sign this application for testing purposes.

Both Mac developer program identities and self-signed certificates are described [in this Apple documentation](https://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html).
